name: Build and Deploy Portfolio
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
    build:
        runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Run a multi-line script
            run: |
                npm build
